services:
  svelte:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: svelte
    ports:
      - 3000:3000
      - 4173:4173
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - my-network
    command: npm run dev

networks:
  my-network:
    driver: bridge
    name: my-network
